USERNAME = ""
PASSWORD = ""
FTP_TARGET_FOLDER = ""
FOLDER_IN_TARGET_FOLDER = ""
FTP_LINK = ""
ABSOLUTE_PATH = ""
TEMP_FILES_FOLDER = r""

# STAC3
WEBSITE = ""
STAC3_USERNAME = ""
STAC3_PASSWORD = ""

# OUTLOOK EMAILS
EMAIL_TO = ""
EMAIL_CC = ""

UNC_PATH_TO_H_DRIVE = r""
TEMP_DIR =  r""
CHROME_PATH = r''

# REGEX
UNIVERSAL_CASE_NUMBER_PATTERN = r''
